svm from scratch
dsgiitr/Assignments pull request #11
Opened 2019-05-17 18:49 UTC by shubhamgit1

2019-05-17 18:55 UTC, AnirudhDagar requested changes
make these changes!

2019-05-17 18:55 UTC, AnirudhDagar commented on assignment_3/chandel svm/README.md
> +##More into the Support_Vector_Machine class
add space here.
## More ....

2019-05-17 18:55 UTC, AnirudhDagar commented on assignment_3/chandel svm/README.md
> +          ![image info](./svm_visualize.png)
```suggestion

          ![image info](./svm_visualize.png)
```

2019-05-20 15:34 UTC, shubhamgit1 commented
sir i made changes as you said

2019-05-20 21:32 UTC, AnirudhDagar commented on assignment_3/README.md
> +11## Problem Statement
remove this error!

2019-05-20 21:33 UTC, AnirudhDagar requested changes
Just a minor  error in 1st line. Chnage that. I'll merge.

2019-05-21 15:49 UTC, shubhamgit1 commented
sir please check i have removed that error

2019-05-28 21:09 UTC, merged