assignment 2
dsgiitr/Assignments pull request #6
Opened 2019-04-12 22:07 UTC by akshit-mittal-1

.

2019-05-08 12:02 UTC, AnirudhDagar requested changes
Looks good!
A few things though...
1. Try to submit a PR next time in a .py file, reviewing is a bit difficult in .ipynb file.
2. Also, function string comments would help. :)

2019-05-08 12:02 UTC, AnirudhDagar commented on assignment_2/akshit/README.md
> +Train a model to print the first n elements of the Fibonacci sequence starting at integers a and b. Note that a < b, and n <= 100 are user supplied arguments. You may not use the standard summing ope
Please correct this.
a=7 b=41 n=6 Output: 7, 41, 48, 89, 137, 226

2019-05-09 10:45 UTC, akshit-mittal-1 commented on assignment_2/akshit/README.md
> +Train a model to print the first n elements of the Fibonacci sequence starting at integers a and b. Note that a < b, and n <= 100 are user supplied arguments. You may not use the standard summing ope
Thanks, and I will keep the above things in ind next time

2019-05-09 10:49 UTC, AnirudhDagar approved these changes

2019-05-09 10:50 UTC, merged

2019-05-09 10:50 UTC, AnirudhDagar commented
Merged this :)
ps. What's up with the SVM assign?

2019-05-09 14:05 UTC, akshit-mittal-1 commented
Hi, working on it, will make a pull request positively by 15th



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/09/19,
7:34:40 PM

On Thu, May 9, 2019 at 4:20 PM Anirudh <notifications@github.com> wrote:

> Merged this :)
> ps. What's up with the SVM assign?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dsgiitr/Assignments/pull/6#issuecomment-490854964>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJ5XTJIQY3CFPM2H73QQ5CTPUP6YNANCNFSM4HFWBJIQ>
> .
>