folder(*): adding SVM model to linearly classify a toy dataset from scratch
dsgiitr/Assignments pull request #7
Opened 2019-05-15 11:29 UTC by subham103

@AnirudhDagar  please review!!

2019-05-15 20:37 UTC, AnirudhDagar requested changes
Great visualization. 👍 for that. Appreciate your efforts.
Just make the required changes in the readme, I'll merge.
Also, the problem statement asked to compare the performance in terms of time to fit the model. It's fine for now though.

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +	- Approach
Get rid of this line "-Approach". Is it incomplete? looks abrupt.

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +    -fit
these points are not getting rendered as expected in a list in markdown.
also when making a list in markdown you need to leave a blank line.
use a space between '-' and 'fit' like below
 ```suggestion
 
    - fit
    - predict 
    - visualize 
```

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +    -predict
```suggestion
```

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +    -visualize
```suggestion

```

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +	- Approach
These are minute changes but please take care about them.

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +    -clone the repo.
same thing here with markdown rendering.

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +    -clone the repo
same

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/README.md
> +5. Visualised the data with the method visualize.
Here you can add the visualized result .png or .jpeg file of the matplotlib figure.
like this 
![image](https://user-images.githubusercontent.com/23621655/57805869-80607a80-777b-11e9-87fb-c84695a561e1.png)

2019-05-15 20:37 UTC, AnirudhDagar commented on assignment_3/SVM_by_subham/svmfrombasic.py
> +    def predict(self, features):
you may have called predict somewhere to show its use. But its okay, just a comment. Keep it as it is for now.

2019-05-16 17:00 UTC, subham103 commented on assignment_3/SVM_by_subham/README.md
> +	- Approach
Actually!! I forgot to delete that line. My bad..

2019-05-16 17:17 UTC, subham103 commented
@AnirudhDagar  I have made the required changes. Please review again..

2019-05-16 19:44 UTC, AnirudhDagar approved these changes

2019-05-16 19:45 UTC, merged